# Generated by Django 4.0.5 on 2022-11-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='talle',
            field=models.CharField(max_length=50),
        ),
    ]
