# Generated by Django 4.0.5 on 2022-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0002_alter_jean_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisa',
            name='talle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.CharField(max_length=50),
        ),
    ]
