# Generated by Django 4.0.5 on 2022-11-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0004_campera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('talle', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
    ]
