# Generated by Django 4.0.5 on 2022-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0006_calzado_alter_jean_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='talle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
