# Generated by Django 4.0.5 on 2022-11-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0007_alter_jean_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jean',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='jean',
            name='talle',
            field=models.CharField(max_length=50),
        ),
    ]
